# Generated by Django 3.0 on 2020-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csb_raw',
            name='decomposed',
            field=models.IntegerField(default=0),
        ),
    ]
