# Generated by Django 2.2.7 on 2019-12-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ur_objects',
            name='is_pob',
            field=models.IntegerField(choices=[(0, 'POB'), (1, 'SE')], default=0),
        ),
    ]
