# Generated by Django 2.2.7 on 2019-12-08 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ur_conn',
            name='user',
            field=models.ForeignKey(null=True, on_delete=models.SET('deleted'), to=settings.AUTH_USER_MODEL),
        ),
    ]
