# Generated by Django 3.0 on 2020-01-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0002_auto_20191210_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff_data',
            name='tariff_schemas',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='tariff_schemas',
        ),
    ]
