# Generated by Django 3.0 on 2020-02-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0002_csb_raw_decomposed'),
    ]

    operations = [
        migrations.AddField(
            model_name='csb_data',
            name='year_date',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='month_date',
            field=models.IntegerField(default=1),
        ),
    ]
