# Generated by Django 3.0 on 2020-01-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0003_auto_20200103_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='zone_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_date', models.DateField()),
                ('zone_schemas', models.CharField(max_length=5)),
                ('hour_1', models.IntegerField()),
                ('hour_2', models.IntegerField()),
                ('hour_3', models.IntegerField()),
                ('hour_4', models.IntegerField()),
                ('hour_5', models.IntegerField()),
                ('hour_6', models.IntegerField()),
                ('hour_7', models.IntegerField()),
                ('hour_8', models.IntegerField()),
                ('hour_9', models.IntegerField()),
                ('hour_10', models.IntegerField()),
                ('hour_11', models.IntegerField()),
                ('hour_12', models.IntegerField()),
                ('hour_13', models.IntegerField()),
                ('hour_14', models.IntegerField()),
                ('hour_15', models.IntegerField()),
                ('hour_16', models.IntegerField()),
                ('hour_17', models.IntegerField()),
                ('hour_18', models.IntegerField()),
                ('hour_19', models.IntegerField()),
                ('hour_20', models.IntegerField()),
                ('hour_21', models.IntegerField()),
                ('hour_22', models.IntegerField()),
                ('hour_23', models.IntegerField()),
                ('hour_24', models.IntegerField()),
            ],
        ),
    ]
