# Generated by Django 3.0 on 2020-02-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0004_auto_20200205_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d1',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d10',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d11',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d12',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d13',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d14',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d15',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d16',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d17',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d18',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d19',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d2',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d20',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d21',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d22',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d23',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d24',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d25',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d26',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d27',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d28',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d29',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d3',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d30',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d31',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d4',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d5',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d6',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d7',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d8',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='tariff_d9',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
