# Generated by Django 3.0 on 2020-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0005_auto_20200205_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csb_data',
            name='value_d1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d13',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d14',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d15',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d16',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d17',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d18',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d19',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d20',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d21',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d22',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d23',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d24',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d25',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d26',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d27',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d28',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d29',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d30',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d31',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='csb_data',
            name='value_d9',
            field=models.FloatField(default=0, null=True),
        ),
    ]
