# Generated by Django 3.0 on 2020-02-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0006_auto_20200207_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='I_COMPANY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_COMPANY_ID', models.IntegerField()),
                ('I_COMPANY_NAME', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'I_COMPANY',
                'managed': False,
            },
        ),
    ]
