# Generated by Django 3.0 on 2020-02-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbil', '0007_i_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='I_COMPANY',
        ),
    ]
